site_name: Datapane Docs
repo_name: datapane/datapane
repo_url: https://github.com/datapane/datapane/
edit_uri: "edit/master/docs/docs/"
copyright: ¬© 2022 <a href="https://datapane.com" target="_blank">Datapane</a>. All rights reserved.

nav:
  - Introduction: "index.ipynb"
  - Quickstart: "quickstart.ipynb"
  - Release Notes: releasenotes.md
  - Tutorials:
      - üå± Getting started:
          - Install Datapane: "tutorials/basics/install-datapane.md"
          - Create an app: "tutorials/basics/create-an-app.ipynb"
      - üß± Blocks types:
          - tutorials/blocks/index.ipynb
      - ‚òÅÔ∏è Datapane Cloud:
          - tutorials/datapane-cloud/index.md
          - Authentication: "tutorials/datapane-cloud/authenticate-datapane.ipynb"
          - Upload an app: "tutorials/datapane-cloud/upload-an-app-to-datapane-cloud.ipynb"
          - App visibility: "tutorials/datapane-cloud/app-visibility.ipynb"
          - Workspaces:
              - "tutorials/datapane-cloud/workspaces/index.md"
              - Workspace settings: "tutorials/datapane-cloud/workspaces/workspace-settings.md"
              - Managing members: "tutorials/datapane-cloud/workspaces/managing-members.md"
          - Projects: "tutorials/datapane-cloud/projects.md"
      - üè¢ Datapane Enterprise:
          - tutorials/datapane-enterprise/index.md
          - Authentication: "tutorials/datapane-enterprise/authenticate-datapane.ipynb"
          - App notifications: "tutorials/datapane-enterprise/app-notifications.ipynb"
          - Files: "tutorials/datapane-enterprise/files.md"
          - Managing members: "tutorials/datapane-enterprise/managing-members.md"
      - üé® Styling:
          - tutorials/styling/index.ipynb
          - Global styling: "tutorials/styling/global-styling.md"
      - ü§ñ Automation:
          - tutorials/automation/index.md

  - Catalogues:
      - "catalogues/index.ipynb"
      - üß± Blocks:
          - "catalogues/blocks/index.ipynb"
          - Tables and data:
              - Big Number: "catalogues/blocks/bignumber.ipynb"
              - Data Table: "catalogues/blocks/datatable.ipynb"
              - Table: "catalogues/blocks/table.ipynb"
          - Plots and visualizations:
              - Plots: "catalogues/blocks/plot.ipynb"
              - Maps: "catalogues/blocks/map.ipynb"
          - Text and HTML:
              - Text: "catalogues/blocks/text.ipynb"
              - Code: "catalogues/blocks/code.ipynb"
              - Formula: "catalogues/blocks/formula.ipynb"
              - HTML: "catalogues/blocks/html.ipynb"
          - Layout and pages:
              - Groups: "catalogues/blocks/group.ipynb"
              - Pages: "catalogues/blocks/page.ipynb"
              - Selects: "catalogues/blocks/select.ipynb"
          # - Divider: "catalogues/blocks/divider.ipynb"
          # - Toggle: "catalogues/blocks/toggle.ipynb"
          - Media and embeds:
              - Attachments: "catalogues/blocks/attachment.ipynb"
              - Embeds: "catalogues/blocks/embed.ipynb"
              - Media: "catalogues/blocks/media.ipynb"
      - üóÉ Components:
          - "catalogues/components/index.ipynb"
          - Calendar heatmap: "catalogues/components/calendar-heatmap.ipynb"
          - Timeline: "catalogues/components/timeline.ipynb"
      - üìë Templates:
          - "catalogues/templates/index.ipynb"

  - Guides:
      - Adding interactive filters to plots: "guides/adding-interactive-filters-to-plots/adding-interactive-filters-to-plots.ipynb"
      - Accessing data in Python: "guides/accessing-data-in-python/accessing-data-in-python.ipynb"

  - Explanations:
      - Datapane Enterprise:
          - "concepts/datapane-enterprise/index.md"
          - Deployment and hosting: "concepts/datapane-enterprise/deployment-and-hosting.md"
          - Authentication and sharing: "concepts/datapane-enterprise/authentication-and-sharing.md"
      - Support policy: "concepts/support-policy.md"

  - Reference:
      - API reference: "https://datapane.github.io/datapane/"

theme:
  name: material
  logo: img/logo.png
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - navigation.indexes
    - content.tabs.link
    #- toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js

plugins:
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      tag_remove_configs:
        remove_cell_tags:
          - remove_cell
        remove_all_outputs_tags:
          - remove_all_output
        remove_single_output_tags:
          - remove_single_output
        remove_input_tags:
          - remove_input
  - search:
      lang: en
  - redirects:
      redirect_maps:
        "tutorials/basics/create-a-report.md": "tutorials/basics/create-an-app.ipynb"
        "tutorials/datapane-cloud/upload-a-report-to-datapane-cloud.md": "tutorials/datapane-cloud/upload-an-app-to-datapane-cloud.ipynb"
        "tutorials/datapane-cloud/report-visibility.md": "tutorials/datapane-cloud/app-visibility.ipynb"
        "tutorials/datapane-enterprise/report-notifications.md": "tutorials/datapane-enterprise/app-notifications.ipynb"

  #- tags
  # Currently a sponsor-only feature
  # - social:
  #     cards_color:
  #       fill: "#131329"
  #       text: "#F2F2FD"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - meta
  - admonition
  - abbr
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  analytics:
    provider: posthog
    api_key: phc_wxtD2Qxd3RMlmCCSYDC0rW1We22yh06cMcffnfSJTZy
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datapane/datapane
    - icon: fontawesome/brands/discourse
      link: https://forum.datapane.com/
    - icon: fontawesome/brands/discord
      link: https://chat.datapane.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datapaneapp
