site_name: Datapane Docs
repo_name: datapane/datapane
repo_url: https://github.com/datapane/datapane/
edit_uri: "edit/master/docs/docs/"
copyright: Â© 2022 <a href="https://datapane.com" target="_blank">Datapane</a>. All rights reserved.

nav:
  - Introduction: "index.ipynb"
  - Quickstart: "quickstart.ipynb"
  - Jupyter Integration: "jupyter-integration.ipynb"
  - Release Notes: releasenotes.md
  - Tutorials:
      - Install Datapane: "tutorials/basics/install-datapane.md"
      - Create an app: "tutorials/basics/create-an-app.ipynb"
      - Add blocks to your app: "tutorials/blocks.ipynb"
      - Datapane Cloud:
          - tutorials/datapane-cloud/index.md
          - Login to Cloud: "tutorials/datapane-cloud/authenticate-datapane.ipynb"
          - Upload your app: "tutorials/datapane-cloud/upload-an-app-to-datapane-cloud.ipynb"
          - Share your app: "tutorials/datapane-cloud/sharing.ipynb"
          - Workspaces:
              - "tutorials/datapane-cloud/workspaces/index.md"
              - Workspace settings: "tutorials/datapane-cloud/workspaces/workspace-settings.md"
              - Managing members: "tutorials/datapane-cloud/workspaces/managing-members.md"
          - Projects: "tutorials/datapane-cloud/projects.md"
      - Styling:
          - Styling a single app: "tutorials/styling/index.ipynb"
          - Global styling: "tutorials/styling/global-styling.md"
      - Automation:
          - tutorials/automation/index.md

  - Catalogs:
      - Catalogs: "catalogs/index.ipynb"
      - ðŸ§± Blocks:
          - Blocks: "catalogs/blocks/index.ipynb"
          - Tables and data:
              - Big Number: "catalogs/blocks/bignumber.ipynb"
              - Data Table: "catalogs/blocks/datatable.ipynb"
              - Table: "catalogs/blocks/table.ipynb"
          - Plots and visualizations:
              - Plots: "catalogs/blocks/plot.ipynb"
              - Maps: "catalogs/blocks/map.ipynb"
          - Text and HTML:
              - Text: "catalogs/blocks/text.ipynb"
              - Code: "catalogs/blocks/code.ipynb"
              - Formula: "catalogs/blocks/formula.ipynb"
              - HTML: "catalogs/blocks/html.ipynb"
          - Layout and pages:
              - Groups: "catalogs/blocks/group.ipynb"
              - Pages: "catalogs/blocks/page.ipynb"
              - Selects: "catalogs/blocks/select.ipynb"
          # - Divider: "catalogs/blocks/divider.ipynb"
          # - Toggle: "catalogs/blocks/toggle.ipynb"
          - Media and embeds:
              - Attachments: "catalogs/blocks/attachment.ipynb"
              - Embeds: "catalogs/blocks/embed.ipynb"
              - Media: "catalogs/blocks/media.ipynb"
      - ðŸ—ƒ Components:
          - Components: "catalogs/components/index.ipynb"
          - Calendar heatmap: "catalogs/components/calendar-heatmap.ipynb"
          - Timeline: "catalogs/components/timeline.ipynb"
      - ðŸ“‘ Templates:
          - Templates: "catalogs/templates/index.ipynb"
  - Reference:
      - API reference: "https://datapane.github.io/datapane/"

theme:
  name: material
  logo: img/logo.png
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - navigation.indexes
    - content.tabs.link
    #- toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: IBM Plex Mono
  favicon: img/favicon.png

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js

plugins:
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      tag_remove_configs:
        remove_cell_tags:
          - remove_cell
        remove_all_outputs_tags:
          - remove_all_output
        remove_single_output_tags:
          - remove_single_output
        remove_input_tags:
          - remove_input
  - search:
      lang: en
  - redirects:
      redirect_maps:
        "tutorials/basics/create-a-report.md": "tutorials/basics/create-an-app.ipynb"
        "tutorials/datapane-cloud/upload-a-report-to-datapane-cloud.md": "tutorials/datapane-cloud/upload-an-app-to-datapane-cloud.ipynb"
        "catalogues/index.md": "catalogs/index.ipynb"
        "catalogues/blocks/index.md": "catalogs/blocks/index.ipynb"
        "catalogues/blocks/bignumber.md": "catalogs/blocks/bignumber.ipynb"
        "catalogues/blocks/datatable.md": "catalogs/blocks/datatable.ipynb"
        "catalogues/blocks/table.md": "catalogs/blocks/table.ipynb"
        "catalogues/blocks/plot.md": "catalogs/blocks/plot.ipynb"
        "catalogues/blocks/map.md": "catalogs/blocks/map.ipynb"
        "catalogues/blocks/text.md": "catalogs/blocks/text.ipynb"
        "catalogues/blocks/code.md": "catalogs/blocks/code.ipynb"
        "catalogues/blocks/formula.md": "catalogs/blocks/formula.ipynb"
        "catalogues/blocks/html.md": "catalogs/blocks/html.ipynb"
        "catalogues/blocks/group.md": "catalogs/blocks/group.ipynb"
        "catalogues/blocks/page.md": "catalogs/blocks/page.ipynb"
        "catalogues/blocks/select.md": "catalogs/blocks/select.ipynb"
        "catalogues/blocks/attachment.md": "catalogs/blocks/attachment.ipynb"
        "catalogues/blocks/embed.md": "catalogs/blocks/embed.ipynb"
        "catalogues/blocks/media.md": "catalogs/blocks/media.ipynb"
        "catalogues/components/index.md": "catalogs/components/index.ipynb"
        "catalogues/components/calendar-heatmap.md": "catalogs/components/calendar-heatmap.ipynb"
        "catalogues/components/timeline.md": "catalogs/components/timeline.ipynb"
        "catalogues/templates/index.md": "catalogs/templates/index.ipynb"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - meta
  - admonition
  - abbr
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  analytics:
    provider: posthog
    api_key: phc_wxtD2Qxd3RMlmCCSYDC0rW1We22yh06cMcffnfSJTZy
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datapane/datapane
    - icon: fontawesome/brands/discourse
      link: https://forum.datapane.com/
    - icon: fontawesome/brands/discord
      link: https://chat.datapane.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datapaneapp
